In [2]:
import pandas as pd

In [3]:
data = {'Region' : ['Korea', 'America', 'China', 'Canada', 'Italy'],
        'Sales' : [300, 200, 500, 150, 50],
        'Amount' : [90, 80, 100, 30, 10],
        'Employee' : [20, 10, 30, 5, 3]
        }

In [4]:
s = pd.Series(data)
s

Region      [Korea, America, China, Canada, Italy]
Sales                     [300, 200, 500, 150, 50]
Amount                       [90, 80, 100, 30, 10]
Employee                        [20, 10, 30, 5, 3]
dtype: object

In [17]:
s.Region

['Korea', 'America', 'China', 'Canada', 'Italy']

In [18]:
s['Region']

['Korea', 'America', 'China', 'Canada', 'Italy']

In [19]:
d = pd.DataFrame(data)
d

Region  Sales  Amount  Employee
0    Korea    300      90        20
1  America    200      80        10
2    China    500     100        30
3   Canada    150      30         5
4    Italy     50      10         3

In [24]:
d['Region']

0      Korea
1    America
2      China
3     Canada
4      Italy
Name: Region, dtype: object

In [29]:
def bubbleSort(x):
	length = len(x)-1
	for i in range(length):
		for j in range(length-i):
			if x[j] > x[j+1]:
				x[j], x[j+1] = x[j+1], x[j]
	return x

In [22]:
a=[1, 4, 2, 8, 6, 7]
bubbleSort(a)

[1, 2, 4, 6, 7, 8]

In [25]:
print("hello world")

hello world


In [146]:
a = [1, 2]
b = [3, 4]

c = a.extend(b)

In [149]:
a

[1, 2, 3, 4]

In [3]:
import numpy as np

np.c_[np.array([1,2,3])]

array([[1],
       [2],
       [3]])

In [20]:
import numpy as np
import matplotlib.pyplot as plt

D1 = np.array([[1.0, 1.2, 3, 4, 5, 6], 
               [1.5, 3, 2.3, 5.3, 3.8, 5.5]])

num_iters = 150 # 선 긋기 횟수
eta = 0.02

np.random.seed(2)
w = np.random.randn(2) # w 초기화
N = D1.shape[1]

ws, L = [], []

# 1열에는 숫자 1이 있고, 2열에는 데이터의 x좌표가 있는 행렬 X를 만듭니다.
# X: (N, 2), y: (N, )
X = np.c_[np.ones(N), D1[0]]
y = D1[1]

# 여기서 우리의 경험 E를 반복하면서 태스크 T를 개선
for i in range(num_iters): 
    # grad L
    c = np.dot(X.T, np.dot(X, w) - y) # 여기 질문 하기 !!
    # 안전장치 grad L을 이용해서 w 수정
    w -= eta * c 
    # w가 변화되는 과정을 저장
    ws.append(w)
    
    # 손실 계산
    L.append( ((np.dot(X, w) - y)**2).sum()/2 )

In [24]:
import numpy as np
import tensorflow as tf

In [27]:
a = np.arange(24).reshape(4, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [26]:
tf.transpose(a)

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 0,  6, 12, 18],
        [ 2,  8, 14, 20],
        [ 4, 10, 16, 22]],

       [[ 1,  7, 13, 19],
        [ 3,  9, 15, 21],
        [ 5, 11, 17, 23]]])>

In [28]:
a = np.reshape(a,(1,4,3,2))

In [29]:
tf.transpose(a)

<tf.Tensor: shape=(2, 3, 4, 1), dtype=int64, numpy=
array([[[[ 0],
         [ 6],
         [12],
         [18]],

        [[ 2],
         [ 8],
         [14],
         [20]],

        [[ 4],
         [10],
         [16],
         [22]]],


       [[[ 1],
         [ 7],
         [13],
         [19]],

        [[ 3],
         [ 9],
         [15],
         [21]],

        [[ 5],
         [11],
         [17],
         [23]]]])>

In [6]:
def tool(prog, speed):
    answer = []
    while(len(prog) >0):
        for i in range(len(prog)):
            prog[i] += speed[i]
            
        q = 0
        while(prog[0] >= 100):
            q += 1
            prog.remove(prog[0])
            speed.remove(speed[0])
            if len(prog) ==0:
                break
        if q >0 :
            answer.append(q)
    return answer

In [7]:
tool([93, 30, 55],[1,30,5])

[2, 1]

In [5]:
import numpy as np

def positional_encoding(pos, d_model):
    def cal_angle(position, i):
        return position / np.power(10000, int(i) / d_model)

    def get_posi_angle_vec(position):
        return [cal_angle(position, i) for i in range(d_model)]

    sinusoid_table = np.array([get_posi_angle_vec(pos_i) for pos_i in range(pos)])

    sinusoid_table[:, 0::2] = np.sin(sinusoid_table[:, 0::2])
    sinusoid_table[:, 1::2] = np.cos(sinusoid_table[:, 1::2])

    return sinusoid_table

pos = 7
d_model = 4
i = 0

print("Positional Encoding 값:\n", positional_encoding(pos, d_model))

print("")
print("if pos == 0, i == 0: ", np.sin(0 / np.power(10000, 2 * i / d_model)))
print("if pos == 1, i == 0: ", np.sin(1 / np.power(10000, 2 * i / d_model)))
print("if pos == 2, i == 0: ", np.sin(2 / np.power(10000, 2 * i / d_model)))
print("if pos == 3, i == 0: ", np.sin(3 / np.power(10000, 2 * i / d_model)))

print("")
print("if pos == 0, i == 1: ", np.cos(0 / np.power(10000, 2 * i + 1 / d_model)))
print("if pos == 1, i == 1: ", np.cos(1 / np.power(10000, 2 * i + 1 / d_model)))
print("if pos == 2, i == 1: ", np.cos(2 / np.power(10000, 2 * i + 1 / d_model)))
print("if pos == 3, i == 1: ", np.cos(3 / np.power(10000, 2 * i + 1 / d_model)))

Positional Encoding 값:
 [[ 0.          1.          0.          1.        ]
 [ 0.84147098  0.99500417  0.00999983  0.9999995 ]
 [ 0.90929743  0.98006658  0.01999867  0.999998  ]
 [ 0.14112001  0.95533649  0.0299955   0.9999955 ]
 [-0.7568025   0.92106099  0.03998933  0.999992  ]
 [-0.95892427  0.87758256  0.04997917  0.9999875 ]
 [-0.2794155   0.82533561  0.05996401  0.999982  ]]

if pos == 0, i == 0:  0.0
if pos == 1, i == 0:  0.8414709848078965
if pos == 2, i == 0:  0.9092974268256817
if pos == 3, i == 0:  0.1411200080598672

if pos == 0, i == 1:  1.0
if pos == 1, i == 1:  0.9950041652780258
if pos == 2, i == 1:  0.9800665778412416
if pos == 3, i == 1:  0.955336489125606


In [14]:
def positional_encoding(pos, d_model):
    def cal_angle(position, i):
        return position / np.power(10000, int(i) / d_model)

    def get_posi_angle_vec(position):
        return [cal_angle(position, i) for i in range(d_model)]

    sinusoid_table = np.array([get_posi_angle_vec(pos_i) for pos_i in range(pos)])
    
    return sinusoid_table

a= positional_encoding(3,1)
a

array([[0.],
       [1.],
       [2.]])

In [17]:
print(np.sin(a[:, 0::2]))

[[0.        ]
 [0.84147098]
 [0.90929743]]


In [18]:
a[:, 0::2]

array([[0.],
       [1.],
       [2.]])

In [19]:
def get_sinusoid_encoding_table(n_seq, d_hidn):
    def cal_angle(position, i_hidn):
        return position / np.power(10000, 2 * (i_hidn // 2) / d_hidn)
    def get_posi_angle_vec(position):
        return [cal_angle(position, i_hidn) for i_hidn in range(d_hidn)]

    sinusoid_table = np.array([get_posi_angle_vec(i_seq) for i_seq in range(n_seq)])
    sinusoid_table[:, 0::2] = np.sin(sinusoid_table[:, 0::2])  # even index sin 
    sinusoid_table[:, 1::2] = np.cos(sinusoid_table[:, 1::2])  # odd index cos

    return sinusoid_table