 ## 5. 텐서의 연산

파이토치에서 다루는 모든 벡터, 행렬, 텐서들에 대해서  
덧셈, 뺄셈, 내적, 외적을 할 수 있습니다.  

In [1]:
import torch as th
from torch import tensor

In [5]:
vec1 = tensor([1, 2, 3])
vec2 = tensor([4, 5, 6])

In [6]:
# 벡터의 dot product를 위해서는 torch.dot 메소드 또는 tensor.dot 메소드를 사용
vec3 = vec1.dot(vec2) # 1*4 + 2*5 + 3*6
print(vec3)

tensor(32)


In [8]:
# 하이퍼 네트워크 : 딥러닝 모델의 가중치를 출력으로 하는 딥러닝 모델

crossed_vec = th.cross(vec1, vec2) # 벡터의 길이가 3차원이어야 함
print(crossed_vec)

tensor([-3,  6, -3])


In [13]:
# * : asterisk 이 기호는 elemnet wise product 수행
vec4 = vec1 * vec2
print(vec4)

# 모든 텐서는 에스터리스크 기호를 통해 원소곱을 수행할 수 있음
mat1 = tensor([[1, 2],
             [3, 4]])
mat2 = tensor([[5, 6],
             [7, 8]])
print(mat1 * mat2)

tensor([ 4, 10, 18])
tensor([[ 5, 12],
        [21, 32]])


In [19]:
# at sign @ : 골뱅이 기호는 행렬곱을 수행하게 됩니다.
# matmul 함수를 통해서도 행렬곱을 계산할 수 있다.

ten1 = tensor([[[1, 2],
             [[3, 4],
              [[5, 6],
              [7, 8]]])
ten2 = tensor([[[5, 6],
             [[7, 8],
              [[9,10],
              [1, 2]]])

a = ten1.matmul(ten2)
b = ten1 @ ten2
print(a)
print(b)

SyntaxError: invalid syntax (<ipython-input-19-4198c6b304a1>, line 7)

## 6. 텐서 차원 조작  *** 중요!!! ***
딥러닝 모델에 데이터를 입력하기 위해 텐서의 차원을 정말 잘 다루어야 합니다.   
이때 차원을 조작하는 메소드로는 다음과 같습니다.

1) 차원 축소, 확장 :  squeeze(), unsqueeze()  
2) 차원 교환 : transpose(), permute() : 순서를 바꾸다.  
3) 차원 조정 : flatten(), view() reshape()  
4) 텐서 합성 및 적재 : cat() stack()  

### 6.1 차원 축소, 확장 :  squeeze(), unsqueeze()  

In [31]:
# torch.ones(shape)를 통해 모든 값이 1인 텐서를 쉽게 만들 수 있다.
tensor_7d = th.ones([10, 32, 1, 1, 64, 64, 3])
tensor_7d = th.zeros([10,32, 1, 1, 64, 64, 3])

# 차원의 모양을 일일히 입력하기 귀찮을 때 like가 붙은 메소드를 사용한다.
tensor_7d2 = th.ones_like(tensor_7d)
tensor_7d3 = th.zeros_like(tensor_7d)
print(tensor_7d.shape)
print(tensor_7d2.shape)

# 항등행렬 .eye 를 통해 만들 수 있다.
eye_tensor = th.eye(2)
# print(eye_tensor)
# print(eye_tensor.shape)

# 항등텐서?
v = th.randn(4)
diag_tensor = th.diag(v)
# print(diag_tensor)
# print(th.sum(diag_tensor))
# print(th.norm(diag_tensor))

torch.Size([10, 32, 1, 1, 64, 64, 3])
torch.Size([10, 32, 1, 1, 64, 64, 3])


In [36]:
# torch.squeeze(axis) 함수는 차원의 크기가 1인 특정 축을 제거합니다.
# axis 값이 없으면 모든 축을 제거합니다.

tensor_6d = tensor_7d.squeeze(axis=2) # shape에서 2번째 인덱스에 해당하는 축 제거
print(tensor_6d.shape)
tensor_5d = tensor_7d.squeeze() # 차원 크기 1인 축 제거
print(tensor_5d.shape)

torch.Size([10, 32, 1, 64, 64, 3])
torch.Size([10, 32, 64, 64, 3])


In [37]:
tensor_4d = th.ones([32, 3, 64, 64])
print(tensor_4d.shape)

torch.Size([32, 3, 64, 64])


In [39]:
# torch.unsqueeze(axis=m) : 차원의 크기가 1인 축을 m번째 인덱스에 추가
# quiz : 0번째 인덱스에 잉여차원을 추가하세요
# 마지막 인덱스에 잉여차원을 추가하세요

tensor_5d = tensor_4d.unsqueeze(axis=0)
tensor_5d2 = tensor_4d.unsqueeze(axis=-1)
print(tensor_5d.shape)
print(tensor_5d2.shape)

torch.Size([1, 32, 3, 64, 64])
torch.Size([32, 3, 64, 64, 1])


### 6.2 차원 교환 : transpose(), permute()  
위 메소드들은 주로 데이터를 변환할 때 많이 사용합니다.  


In [40]:
matrix = th.ones([2,3])
print(matrix.shape)

torch.Size([2, 3])


In [49]:
# torch.transpose(input, dim0, dim1) 는 인풋 텐서의 두 차원을 교환
transposed = th.transpose(matrix, 0 ,1)
print(transposed.shape)
transposed2 = matrix.transpose(0 ,1)
print(transposed2.shape)

tensor_4d = th.ones([4, 2, 6, 11])
print(tensor_4d.shape)
# 퀴즈 : 0번째, 2번째 차원을 교환하세요
transposed3 = th.transpose(tensor_4d, 0 ,2)
print(transposed3.shape)



torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([4, 2, 6, 11])
torch.Size([6, 2, 4, 11])


In [55]:
# torch.permute() : transpose의 상위버전 메소드. 차원 축 순서를 원하는대로 나열
# quiz : tensor_4d의 차원축을 내림차순으로 정렬하세요.
# 텐서 순서 조정은 직접 해야한다.
print(tensor_4d.shape)

permuted = tensor_4d.permute(3, 2, 1, 0)
# permuted = th.permute(tensor_4d, 3, 2, 1, 0)
print(permuted.shape)

torch.Size([4, 2, 6, 11])
torch.Size([11, 6, 2, 4])


### 6.3 차원 조정 : flatten(),  reshape(), view()  
위 세 가지 메소드는 주로 CNN 레이어에서 FC 레이어로 오고 갈 때 자주 사용합니다.  

In [60]:
# torch.flatten() 메소드는 텐서 전체를 1차원 텐서로 변환
t = tensor([[[1, 2],
           [3, 4]],
           [[5, 6],
           [7, 8]]])
print(t.shape)

torch.Size([2, 2, 2])


In [61]:
flattened_t = th.flatten(t)
print(flattened_t)
print(flattened_t.shape)

tensor([1, 2, 3, 4, 5, 6, 7, 8])
torch.Size([8])


In [ ]:
# 만약에 start_dim, end_dim이 주어지면 해당하는 차원부터 flatten 합니다.
flattened_t2 = th.

In [62]:
# reshape() 메소드는 텐서를 원하는 모양을 가지도록 차원을 조정합니다.
# 단 이때, 각 차원의 총 형태가 원래의 차원과 일치해야합니다. ex 8 ->2, 2, 2 or 4, 2
t2 = th.arange(36)
t2.shape

torch.Size([36])

In [66]:
# quiz : t2의 모양을 (3, 3, 4)로 바꿔보세요
reshaped_t = t2.reshape(3, 3, 4)
print(reshaped_t.shape)

torch.Size([3, 3, 4])


In [69]:
# torch.view(-1, m, ...) 차원의 크기가 아주 크고 복잡해서 reshape를 통해 일일히 계산하기
# reshape도 되긴 함.
t3 = th.arange(24940)
# 이때 -1 값이 들어가면 나머지 차원 축의 크기를 자동으로 계산
# quiz : 두 개의 차원 축 값이 (5, 4, ?)인 텐서를 만드세요
viewed_t1 = t3.view(5, 4, -1)
print(viewed_t1.shape)

torch.Size([5, 4, 1247])


### 6.4 텐서 합성 및 적재 : cat() stack()  
마지막으로 텐서를 합성하기 위해 cat()과 stack()을 활용합니다.  
cat() 함수는 모델 내부에서 다음 은닉층에 들어가는 텐서들을 조합하기 위해 주로 사용합니다.  

stack() 함수는 데이터를 쌓아서 미니배치를 구성할 때 주로 사용합니다.  

In [72]:
# torch.cat() 함수는 두 개 이상의 텐서 시퀀스를 합치게 됩니다.
# 해당 텐서들의 차원은 반드시 같아야 합니다.
vec1 = tensor([1, 2, 3])
vec2 = tensor([4, 5, 6])
vec3 = tensor([7, 8, 9])
vec4 = th.cat([vec1, vec2, vec3])
print(vec4.shape) # 1차원으로 쭉 이어붙임

torch.Size([9])


In [82]:
# stack() 메소드는 두 개 이상의 텐서들을 특정 축을 기준으로 쌓게 됩니다
batch_vec = th.stack([vec1, vec2, vec3], dim=0)
print(batch_vec)
print(batch_vec.shape)

batch_vec2 = th.stack([vec1, vec2, vec3], dim=1)
print(batch_vec2)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [ ]:
th.mean()
th.sum()
th.min()
th.argmin()
th.max()
th.argmax()

# 퀴즈 (Hard)
1) 길이가 4096인 랜덤벡터를 하나 생성하세요.  
2) 벡터를 위에서 배운 메소드들 중 하나를 이용해 (64x64) 정사각행렬로 차원을 조정하세요.   
3) 1, 2의 과정을 반복해서 정사각행렬을 세 개 만든다음, 각각 텐서의 0번째 축에 크기가 1인 잉여차원을 추가하세요.  
4) 0번째 축과 마지막 축을 교환하세요.   
5) 리스트에 세 개의 정사각행렬을 담아서 마지막 축을 기준으로 텐서를 합성하세요 -> 64x64x3 텐서가 나와야함  
6) 위의 과정을 4번 반복해서 64x64x3 를 쌓아서 4 x 64 x 64 x 3 텐서를 만드세요  

In [102]:
th.manual_seed(1030)
# code : 

# 1)
rand_vec1 = th.randn(4096)
rand_vec2 = th.randn(4096)
rand_vec3 = th.randn(4096)

# 2)
reshape_vec1 = rand_vec1.reshape(64, 64)
reshape_vec2 = rand_vec2.reshape(64, 64)
reshape_vec3 = rand_vec3.reshape(64, 64)

# 3)
unsqueeze_vec1 = reshape_vec1.unsqueeze(axis=0)
unsqueeze_vec2 = reshape_vec2.unsqueeze(axis=0)
unsqueeze_vec3 = reshape_vec3.unsqueeze(axis=0)

# 4)
trans_vec1 = unsqueeze_vec1.transpose(0,-1)
trans_vec2 = unsqueeze_vec2.transpose(0,-1)
trans_vec3 = unsqueeze_vec3.transpose(0,-1)
print(trans_vec1.shape)


# 5)
list_vec = [trans_vec1, trans_vec2, trans_vec3]

cat_ten = [th.cat(list_vec, dim=-1) for i in range(4)]
print(cat_ten[0].shape)

# 6)
stack_ten = th.stack(cat_ten, dim=0)

print(stack_ten.shape)

torch.Size([64, 64, 1])
torch.Size([64, 64, 3])
torch.Size([4, 64, 64, 3])
