In [38]:
import numpy as np

x1 = np.array([0.5,0.2])
# x2 = np.array([0.1,0.8])
h0 = np.array([0, 0])

w_xh = np.array([[0.2, -0.5], [0.8, 0.1]])
w_hh = np.array([[1,0], [0.4, -2]])
w_hy = np.array([[0.5, -0.2], [0.3, 0.5]])


In [39]:
def relu(x):
    return np.maximum(0, x)

In [40]:
def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()

In [41]:
h1 = relu((w_hh@h0)+(w_xh@x1))
h1

array([0.  , 0.42])

In [42]:
y1 = softmax(h1@w_hy)
y1

array([0.47901234, 0.52098766])

In [43]:
h2= relu((w_hh@h1)+(w_xh@y1))
h2

array([0., 0.])

In [44]:
y2 = softmax(h2@w_hy)
y2

array([0.5, 0.5])

In [45]:
import numpy as np

W_hh = np.array([[1, 0], [0.4, -2]])
W_xh = np.array([[0.2, -0.5], [0.8, 0.1]])
W_hy = np.array([[0.5, -0.2], [0.3, 0.5]])

def ReLU(x):
    return np.maximum(x, 0)

def Softmax(x:np.array):
    exp_x = np.exp(x)
    return exp_x / exp_x.sum()

def Sigmoid(x):
    return 1/1+np.exp(-x)

x1 = [0.5, 0.2]
h0 = [0, 0]
u1 = W_hh.dot(h0) + W_xh.dot(x1)
h1 = ReLU(u1)
y1 = Softmax(W_xh.dot(h1))
print(u1)
print(h1)
print(y1)

x2 = y1
u2 = W_hh.dot(h1) + W_xh.dot(x2)
h2 = ReLU(u2)
y2 = Softmax(W_hy.dot(h2))
print(u2)
print(h2)
print(y2)

[0.   0.42]
[0.   0.42]
[0.43733129 0.56266871]
[-0.1938681 -0.4338681]
[0. 0.]
[0.5 0.5]
